include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    public_member_api_docs: ignore
    use_to_and_as_if_applicable: ignore
