name: typesafe_postgrest
description: A dart package that enables type-safe PostgREST queries.
version: 0.0.1-dev.1
repository: https://github.com/JakesMD/typesafe-postgrest

environment:
  sdk: ^3.8.0

dependencies:
  meta: ^1.17.0
  postgrest: ^2.4.2

dev_dependencies:
  very_good_analysis: ^9.0.0
