name: typesafe_postgrest
description: A dart package that enables type-safe PostgREST queries.
version: 0.2.5
repository: https://github.com/JakesMD/typesafe-postgrest

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^7.4.5
  build: ^2.5.3
  meta: ^1.16.0
  postgrest: ^2.4.2
  source_gen: ^2.0.0

dev_dependencies:
  very_good_analysis: ^9.0.0
